# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_credit_half_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='last_change',
            field=models.TimeField(auto_now=True),
        ),
    ]
