# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('complexity', models.PositiveIntegerField(choices=[(2, 'Low'), (2.5, 'Normal'), (3, 'High')])),
                ('min_bet', models.PositiveIntegerField()),
                ('max_bet', models.PositiveIntegerField()),
            ],
        ),
    ]
