# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 12:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('station_name', models.CharField(max_length=30)),
                ('complexity', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d{2,3}$')])),
                ('min_bet', models.PositiveIntegerField()),
                ('max_bet', models.PositiveIntegerField()),
            ],
        ),
    ]
