# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='owner',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
