# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='station_name',
            new_name='name',
        ),
    ]
