# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': (('station', 'Can view "/station" page'),)},
        ),
    ]
