# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='complexity',
            field=models.FloatField(),
        ),
    ]
