# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20180509_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='complexity',
            field=models.PositiveIntegerField(choices=[(2, 'Low'), (2.5, 'Normal'), (3, 'High')]),
        ),
    ]
