# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0011_auto_20180829_1251'),
        ('banks', '0003_auto_20180829_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('money_amount', models.PositiveIntegerField(default=0)),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bank', to='banks.Bank')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_team', to='teams.Team')),
            ],
        ),
    ]
