# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-30 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='money_amount',
            new_name='invest_amount',
        ),
    ]
