# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_deposit_half_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='half_year',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='invest_amount',
            field=models.FloatField(default=0),
        ),
    ]
