# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_deposit_half_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='last_change',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
