# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0007_deposit_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='last_change',
            field=models.TimeField(auto_now=True),
        ),
    ]
