# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sender_id', models.PositiveIntegerField(default=None)),
                ('recipient_id', models.PositiveIntegerField(default=None)),
                ('amount', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('recipient_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='contenttypes.ContentType')),
                ('sender_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='contenttypes.ContentType')),
            ],
        ),
    ]
