# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
    ]
