# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0002_remove_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
