# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
