# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180827_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.PositiveIntegerField(),
        ),
    ]
