# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_station', "Can view '/admin/add_station/' page"),)},
        ),
    ]
