# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180821_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_station', "Can view '/admin/add_station/' page"), ('add_team', "Can view '/admin/add_team/' page"), ('view_shares_list', "Can view '/admin/shares_list/' page"), ('confirm_transaction', "Can view '/admin/confirm_transaction/' page"), ('view_shadow_economy', "Can view '/admin/shadow_economy/' page"), ('view_station_transactions', "Can view '/admin/station_transactions/' page"), ('view_debit_list', "Can view '/admin/debit_list/' page"), ('view_credit_list', "Can view '/admin/credit_list/' page"), ('view_start', "Can view '/admin/start/' page"))},
        ),
    ]
