# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180819_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterModelOptions(
            name='stationadmin',
            options={'permissions': (('view_station', "Can view '/station' page"),)},
        ),
    ]
