# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-04 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180904_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'permissions': (('view_deposit', "Can view '/admin/deposit/' page"), ('view_credit', "Can view '/admin/credit/' page"), ('view_give_money', "Can view '/admin/give_money/' page"), ('view_confirm_transaction', "Can view '/admin/confirm_transaction/' page"), ('add_group', "Can view '/admin/add_group/' page"))},
        ),
    ]
