# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0012_auto_20180830_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('half_year', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('amount', models.FloatField()),
                ('stock_price', models.ManyToManyField(related_name='sharetype', to='shares.ShareRate')),
            ],
        ),
        migrations.AddField(
            model_name='sharedeal',
            name='share_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_deal', to='shares.ShareType'),
        ),
        migrations.AddField(
            model_name='sharedeal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
