# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetype',
            name='stock_price',
            field=models.ManyToManyField(related_name='share_type', to='shares.ShareRate'),
        ),
    ]
