# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('deposit', models.FloatField()),
                ('credit_for_one_year', models.FloatField()),
                ('credit_for_two_years', models.FloatField()),
            ],
        ),
    ]
