# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20180827_1017'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('debt_amount', models.PositiveIntegerField(default=0)),
                ('term', models.PositiveIntegerField(default=1)),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credit_bank', to='banks.Bank')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credit_team', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('money_amount', models.PositiveIntegerField(default=0)),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bank', to='banks.Bank')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_team', to='teams.Team')),
            ],
        ),
    ]
