# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='pay_pass',
            new_name='chip_number',
        ),
    ]
