# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20180830_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='money_amount',
            field=models.FloatField(),
        ),
    ]
