# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 10:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='login',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
