# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180509_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
