# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180515_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='login',
        ),
        migrations.AddField(
            model_name='team',
            name='bank',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='faculty',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='card',
            field=models.CharField(max_length=25),
        ),
    ]
