# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180824_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='money_amount',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='pay_pass',
            field=models.CharField(default=None, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='bank',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='card',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
