# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20180826_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='team',
            name='money_amount',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pay_pass',
        ),
        migrations.AddField(
            model_name='card',
            name='pay_pass',
            field=models.CharField(default=None, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
