# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_card_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='card_method',
            new_name='card_type',
        ),
    ]
