# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20180827_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='card_type',
        ),
        migrations.AlterField(
            model_name='team',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_bank', to='banks.Bank'),
        ),
        migrations.AlterField(
            model_name='team',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_card', to='cards.Card'),
        ),
    ]
